blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Pralhad-Nasane/gmail-filters-collection/blob/main/README.md
    about: Check the README for setup instructions and package details